# Generated by Django 5.0.3 on 2024-05-06 18:08

import sitterlist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[sitterlist.models.validate_letters])),
                ('gender', models.CharField(max_length=10, validators=[sitterlist.models.validate_letters])),
                ('location', models.CharField(max_length=100, validators=[sitterlist.models.validate_letters])),
                ('date_of_birth', models.DateField()),
                ('nin', models.CharField(max_length=14, validators=[sitterlist.models.validate_NIN_length])),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Religion(optional)')),
                ('education', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Others', 'Others')], max_length=100)),
                ('contact', models.CharField(default='', max_length=15, validators=[sitterlist.models.validate_contact_length])),
                ('sitter_number', models.CharField(max_length=200, null=True, unique=True)),
                ('next_of_kin', models.CharField(max_length=100, validators=[sitterlist.models.validate_letters])),
                ('recommender_name', models.CharField(max_length=100, validators=[sitterlist.models.validate_letters])),
                ('recommender_contact', models.CharField(default='', max_length=15, validators=[sitterlist.models.validate_contact_length])),
            ],
        ),
    ]
