# Generated by Django 5.0.3 on 2024-04-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nin',
            field=models.CharField(default='CF', max_length=15),
        ),
    ]
