# Generated by Django 5.0.3 on 2024-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterlist', '0002_alter_student_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nin',
            field=models.CharField(max_length=15),
        ),
    ]
