# Generated by Django 5.0.3 on 2024-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitterlist', '0002_delete_sitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nin', models.CharField(max_length=15)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(max_length=100)),
                ('contact', models.CharField(default='', max_length=15)),
                ('sitter_number', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('recommender_name', models.CharField(max_length=100)),
                ('recommender_contact', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
