# Generated by Django 5.0.3 on 2024-05-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitterlist', '0004_sitter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitter',
        ),
    ]
