# Generated by Django 5.0.3 on 2024-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity_received', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('date_received', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='procurementrecord',
            name='item',
        ),
        migrations.DeleteModel(
            name='ProcurementItem',
        ),
        migrations.DeleteModel(
            name='ProcurementRecord',
        ),
    ]
