# Generated by Django 5.0.3 on 2024-05-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_remove_item_category_remove_item_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
