# Generated by Django 5.0.3 on 2024-05-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_supply_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='change_received',
            field=models.IntegerField(default=0),
        ),
    ]
