# Generated by Django 5.0.3 on 2024-05-07 05:07

import babyform.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendancestatus', models.CharField(choices=[('onduty', 'onduty')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[babyform.models.validate_letters])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('age', models.IntegerField(validators=[babyform.models.validate_numbers])),
                ('location', models.CharField(max_length=100, validators=[babyform.models.validate_letters])),
                ('brought_by', models.CharField(default='', max_length=100, validators=[babyform.models.validate_letters])),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parents_names', models.CharField(max_length=200, null=True, validators=[babyform.models.validate_letters])),
                ('fee', models.CharField(default='UGX 0', max_length=20, validators=[babyform.models.validate_numbers])),
                ('period_of_stay', models.CharField(max_length=100, validators=[babyform.models.validate_letters])),
                ('baby_number', models.CharField(max_length=500, null=True, unique=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babyform.sitter')),
            ],
        ),
    ]
