# Generated by Django 5.0.3 on 2024-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='on_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='attendancestatus',
            field=models.CharField(choices=[('on_duty', 'on_duty')], default='', max_length=100),
        ),
    ]
