# Generated by Django 5.0.3 on 2024-04-25 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='assigned_sitter',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='baby_deliverer',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='fee_paid',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='parent_names',
        ),
        migrations.AddField(
            model_name='baby',
            name='brought_by',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='baby',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baby',
            name='parents_names',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='baby',
            name='baby_number',
            field=models.IntegerField(default=''),
        ),
    ]
