# Generated by Django 5.0.3 on 2024-04-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyform', '0002_remove_baby_assigned_sitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='brought_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='baby',
            name='fee',
            field=models.CharField(default='UGX 0', max_length=20),
        ),
    ]
