# Generated by Django 5.0.3 on 2024-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyform', '0002_sitter_on_duty_alter_sitter_attendancestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='attendancestatus',
            field=models.CharField(choices=[('on_duty', 'on_duty')], default='on_duty', max_length=100),
        ),
    ]
