# Generated by Django 5.0.3 on 2024-04-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyform', '0003_alter_baby_brought_by_alter_baby_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_on_duty', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='assigned_sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='babyform.sitter'),
        ),
    ]
