# Generated by Django 5.0.3 on 2024-04-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitterform', '0006_alter_sitter_contact_alter_sitter_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitter',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
