# Generated by Django 5.0.3 on 2024-04-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterform', '0007_rename_dob_sitter_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
