# Generated by Django 5.0.3 on 2024-04-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterform', '0008_alter_sitter_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='contact',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='recommender_contact',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
