# Generated by Django 5.0.3 on 2024-04-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterform', '0009_alter_sitter_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='recommender_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
