# Generated by Django 5.0.3 on 2024-04-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterform', '0010_alter_sitter_contact_alter_sitter_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='nin',
            field=models.CharField(max_length=15),
        ),
    ]
