# Generated by Django 5.0.3 on 2024-04-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterform', '0012_alter_sitter_recommender_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='recommender_contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='sitter_number',
            field=models.CharField(max_length=100),
        ),
    ]
