# Generated by Django 5.0.3 on 2024-05-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='babies_attended',
            field=models.IntegerField(default=0),
        ),
    ]
