# Generated by Django 5.0.3 on 2024-05-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_sitter_babies_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='babies_attended',
            field=models.IntegerField(default=0),
        ),
    ]
