# Generated by Django 5.0.3 on 2024-05-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_payment_babies_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='baby',
        ),
        migrations.DeleteModel(
            name='Baby',
        ),
    ]
