# Generated by Django 5.0.3 on 2024-05-03 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(max_length=100)),
                ('baby_deliverer', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
