# Generated by Django 5.0.3 on 2024-05-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='change_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
