# Generated by Django 5.0.3 on 2024-05-10 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsitter', '0003_remove_payment_baby_payment_baby_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='change_received',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='actual_amount',
            field=models.IntegerField(choices=[(10000, '10000'), (15000, '15000'), (300000, '300000'), (450000, '450000')], default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='baby_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('halfday', 'halfday'), ('fullday', 'fullday'), ('monthlyhalfday', 'monthlyhalfday'), ('monthlyfullfday', 'monthlyfullday')], max_length=100),
        ),
    ]
