# Generated by Django 5.0.3 on 2024-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsitter', '0004_remove_payment_change_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='actual_amount',
            field=models.IntegerField(choices=[(10000, '10000'), (15000, '15000')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('halfday', 'halfday'), ('fullday', 'fullday')], max_length=100),
        ),
    ]
