# Generated by Django 5.0.3 on 2024-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsitter', '0005_alter_payment_actual_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='actual_amount',
            field=models.IntegerField(choices=[(10000, '10000'), (15000, '15000'), (300000, '300000'), (450000, '450000')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('halfday', 'halfday'), ('fullday', 'fullday'), ('monthlyhalfday', 'monthlyhalfday'), ('monthlyfullfday', 'monthlyfullday')], max_length=100),
        ),
    ]
