# Generated by Django 5.0.3 on 2024-05-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsitter', '0006_alter_payment_actual_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='baby_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='baby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsitter.baby'),
        ),
    ]
