# Generated by Django 5.0.3 on 2024-04-27 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycheck', '0002_remove_babydeparture_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='babydeparture',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
