# Generated by Django 5.0.3 on 2024-05-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babycheck', '0003_babydeparture_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='babydeparture',
            name='baby_name',
        ),
        migrations.AddField(
            model_name='babydeparture',
            name='baby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='babycheck.baby'),
        ),
    ]
