# Generated by Django 5.0.3 on 2024-05-02 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='unit_price',
        ),
    ]
