# Generated by Django 5.0.3 on 2024-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
